language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-raadhuis' ]; then cd .. && eval "mv $currentfolder generator-raadhuis" && cd generator-raadhuis; fi
